### ISSUE TITLE
niz68魔改外壳询问

### ISSUE THREAD

**Issue by ghost** [soragotosann/niz68_material#1]
你这里面的图片好像打不开，我也会niz68想考虑整个外壳，能看看你的魔改效果吗，感谢！

**Comment by dev-soragoto** [comment]
> 你这里面的图片好像打不开，我也会niz68想考虑整个外壳，能看看你的魔改效果吗，感谢！

你可以尝试直接把整个项目clone下来，github国内有墙可能是挺慢的，不过我得那个外壳的图纸不是很准确，你可能需要自己修改， 直接拿去用的话可能有问题，定位板是可以直接用的
