### ISSUE TITLE
定位板

### ISSUE THREAD

**Issue by UndefBhvr** [soragotosann/niz68_material#2]
老哥换定位板麻烦吗，一直想换个碳定

**Comment by dev-soragoto** [comment]
> 老哥换定位板麻烦吗，一直想换个碳定

我感觉还行吧 一个一个拆轴和推杆挺费事的 不过没啥难度 你自己拆了看看吧

**Comment by UndefBhvr** [comment]
ok谢谢捏，现在暂时先用原厂，有空了去切个碳定看看

**Comment by dev-soragoto** [comment]
> ok谢谢捏，现在暂时先用原厂，有空了去切个碳定看看

好的 那issue我就关掉了
